### ISSUE TITLE
why not put one in a dockerfile to make it easier?

### ISSUE THREAD

**Issue by Zxce3** [Crownss/dark_market#21]
Wouldn't it be easier if everything became one from the start to compile to deploy, just setting the env
and one more thing, for the payment method, make it so that it can be set on the env

**Comment by Crownss** [comment]
i have a plan to create golang and postgresql in 1 docker with compose to make it simple
and maybe i'll upload the single image(only golang postgres not include) to docker hub
**Stay Tune !**
